services:
  # Base de datos PostgreSQL para desarrollo
  postgres:
    image: postgres:15-alpine
    container_name: autograder_postgres_dev
    environment:
      POSTGRES_DB: autograder
      POSTGRES_USER: autograder_user
      POSTGRES_PASSWORD: autograder_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./infrastructure/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"  # Puerto diferente para evitar conflictos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autograder_user -d autograder"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: autograder_redis_dev
    ports:
      - "6380:6379"  # Puerto diferente para evitar conflictos
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
